# Generated by Django 3.0.5 on 2020-05-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='API Name')),
                ('usage', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('link', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='API_Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.API')),
            ],
        ),
    ]
