# Generated by Django 3.0.5 on 2020-05-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='API_Variant',
            new_name='APIVariant',
        ),
    ]
